/* eslint-disable */
// Generated by gulp svg-icon - do not modify manually
import React, { PureComponent as Component } from 'react';
import PropTypes from 'prop-types';

const iconList = [
  'categories',
  'chevron-bottom',
  'chevron-left',
  'chevron-right',
  'chevron-top',
  'home',
  'menu',
  'search'
];

class Icon extends Component {
  static propTypes = {
    className: PropTypes.string,
    color: PropTypes.string,
    height: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    width: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    kind: PropTypes.oneOf([
      'categories',
      'chevron-bottom',
      'chevron-left',
      'chevron-right',
      'chevron-top',
      'home',
      'menu',
      'search'
    ]).isRequired,
    onClick: PropTypes.func,
    preview: PropTypes.bool,
    size: PropTypes.number,
    style: PropTypes.oneOfType([PropTypes.array, PropTypes.object]),
    wrapperStyle: PropTypes.oneOfType([PropTypes.array, PropTypes.object])
  };

  static defaultProps = {
    color: '#000',
    size: 32
  };

  render() {
    const { kind, preview } = this.props;

    return preview ? this.renderPreview() : this.renderIcon(kind);
  }

  renderPreview() {
    return <div>{iconList.map(kind => this.renderPreviewKind(kind))}</div>;
  }

  renderIcon(kind) {
    const { wrapperStyle } = this.props;

    if (wrapperStyle)
      return <div style={wrapperStyle}>{this.getIcon(kind)}</div>;

    return this.getIcon(kind);
  }

  renderPreviewKind(kind) {
    return (
      <div key={kind}>
        <h3>&lt;Icon kind="{kind}" /&gt;</h3>
        {this.renderIcon(kind)}
      </div>
    );
  }

  getIcon(kind) {
    const {
      height,
      color,
      onClick,
      size,
      style,
      width,
      className,
      ...rest
    } = this.props;

    switch (kind) {
      default:
        return null;
      case 'categories':
        return (
          <svg
            id="Capa_1"
            {...rest}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 341.333 341.333"
          >
            <path d="M128 128h85.333v85.333H128zM0 0h85.333v85.333H0zM128 256h85.333v85.333H128zM0 128h85.333v85.333H0zM0 256h85.333v85.333H0zM256 0h85.333v85.333H256zM128 0h85.333v85.333H128zM256 128h85.333v85.333H256zM256 256h85.333v85.333H256z" />
          </svg>
        );
      case 'chevron-bottom':
        return (
          <svg
            id="Layer_1"
            {...rest}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 32 32"
          >
            <title>chevron-bottom</title>
            <path
              id="chevron-right"
              d="M14.83 24.12L1.48 11.55a1.49 1.49 0 0 1 0-2.2L3 7.88a1.72 1.72 0 0 1 2.33 0L16 17.84l10.63-10a1.72 1.72 0 0 1 2.33 0l1.56 1.47a1.49 1.49 0 0 1 0 2.2L17.17 24.12a1.72 1.72 0 0 1-2.34 0z"
            />
          </svg>
        );
      case 'chevron-left':
        return (
          <svg
            id="Layer_1"
            {...rest}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 32 32"
          >
            <title>chevron-left</title>
            <path
              id="chevron-right"
              d="M7.88 14.83L20.45 1.48a1.49 1.49 0 0 1 2.2 0L24.12 3a1.72 1.72 0 0 1 0 2.33L14.16 16l10 10.63a1.72 1.72 0 0 1 0 2.33l-1.47 1.56a1.49 1.49 0 0 1-2.2 0L7.88 17.17a1.72 1.72 0 0 1 0-2.34z"
            />
          </svg>
        );
      case 'chevron-right':
        return (
          <svg
            id="Layer_1"
            {...rest}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 32 32"
          >
            <title>chevron-right</title>
            <path
              id="chevron-right"
              d="M24.12 17.17L11.55 30.52a1.49 1.49 0 0 1-2.2 0L7.88 29a1.72 1.72 0 0 1 0-2.33L17.84 16 7.88 5.37a1.72 1.72 0 0 1 0-2.37l1.47-1.52a1.49 1.49 0 0 1 2.2 0l12.57 13.35a1.72 1.72 0 0 1 0 2.34z"
            />
          </svg>
        );
      case 'chevron-top':
        return (
          <svg
            id="Layer_1"
            {...rest}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 32 32"
          >
            <title>chevron-top</title>
            <path
              id="chevron-right"
              d="M17.17 7.88l13.35 12.57a1.49 1.49 0 0 1 0 2.2L29 24.12a1.72 1.72 0 0 1-2.33 0L16 14.16l-10.63 10a1.72 1.72 0 0 1-2.33 0l-1.56-1.51a1.49 1.49 0 0 1 0-2.2L14.83 7.88a1.72 1.72 0 0 1 2.34 0z"
            />
          </svg>
        );
      case 'home':
        return (
          <svg
            id="Layer_1"
            {...rest}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 32 32"
          >
            <title>home</title>
            <path d="M30.7 16.78L17 2.83a1 1 0 0 0-1.47 0L1.32 16.76a1.06 1.06 0 0 0-.24 1.16 1 1 0 0 0 1 .65h2.4v9.85a1.05 1.05 0 0 0 1 1.06h7.16a1.05 1.05 0 0 0 1-1.06v-7.21H18v7.21a1.05 1.05 0 0 0 1 1.06h6.81a1.05 1.05 0 0 0 1-1.06v-9.85h3a1 1 0 0 0 1-.65 1.07 1.07 0 0 0-.11-1.14zm-4.75-.32a1.05 1.05 0 0 0-1 1.06v9.85h-4.76v-7.21a1.05 1.05 0 0 0-1-1.06h-6.51a1.05 1.05 0 0 0-1 1.06v7.21H6.57v-9.85a1.05 1.05 0 0 0-1-1.06h-.95L16.28 5.07l11.17 11.4z" />
          </svg>
        );
      case 'menu':
        return (
          <svg
            id="Layer_1"
            {...rest}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 32 32"
          >
            <title>menu</title>
            <path d="M30.1 3.31H1.9a.84.84 0 0 0-.9.92v2.62a.84.84 0 0 0 .9.92h28.2a.84.84 0 0 0 .9-.92V4.23a.84.84 0 0 0-.9-.92zM30.1 24.23H1.9a.84.84 0 0 0-.9.92v2.62a.85.85 0 0 0 .9.92h28.2a.85.85 0 0 0 .9-.92v-2.62a.84.84 0 0 0-.9-.92zM30.1 13.77H1.9a.84.84 0 0 0-.9.92v2.62a.84.84 0 0 0 .9.92h28.2a.84.84 0 0 0 .9-.92v-2.62a.84.84 0 0 0-.9-.92z" />
          </svg>
        );
      case 'search':
        return (
          <svg
            id="Layer_1"
            {...rest}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 32 32"
          >
            <title>search</title>
            <path d="M12.64 1h-.05A11.59 11.59 0 0 0 1 12.66a11.84 11.84 0 0 0 11.73 11.75 11.61 11.61 0 0 0 6.86-2.26l.18-.13.16.15 8.35 8.35a1.55 1.55 0 1 0 2.19-2.18L22 19.82l.13-.18a11.65 11.65 0 0 0 2.24-6.89A11.84 11.84 0 0 0 12.64 1zm7 18.67a9.79 9.79 0 0 1-6.89 2.86 9.93 9.93 0 0 1-9.84-9.85 9.73 9.73 0 0 1 9.74-9.79 9.93 9.93 0 0 1 9.84 9.86 9.79 9.79 0 0 1-2.84 6.92z" />
          </svg>
        );
    }
  }
}

export default Icon;
